[package]
name = "pwned_pwd_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }