[package]
name = "pwned_pwd_store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pwned_pwd_core = { path = "../pwned_pwd_core" }

futures = { workspace = true }